### PR TITLE
Hdf storage, plots and UTC

### PR DESCRIPTION
**Pull request by FMassin**
See commit messages. Should fix issue https://github.com/ThomasLecocq/SeismoRMS/issues/16

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
didn't test it but if all test pass on your machine , then it's ok for me, merge it.

I'll add the try-except on the get_waveforms right after (#17 )

**Comment by FMassin** [comment]
Something is wrong, I'll fix it ...

**Comment by FMassin** [comment]
Now it is fixed :)

Capture d’écran 2020-05-01 à 19 42 28

**Comment by FMassin** [comment]
Done.

**Pull request merged**
