### PR TITLE
Multi-stations/channels support

### PR DESCRIPTION
**Pull request by FMassin**
This add support for processing all channels of several stations.

This is also sugesting to use the euclidian sum of RMS from all
channels rather than the Z channel only.

There are also little suggestions:
- Use median resampling.
- Display all channels of the same station on final figure(s).
- Add legend on final figure(s).
- Add logo on final figure(s).

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Looks good to me.

Only question the seed channels = `HG*` is an gravimeter ? (according to https://ds.iris.edu/ds/nodes/dmc/tools/data_channels/#HG?) ?

**Comment by FMassin** [comment]
No this how SED labels accelerometers... historical reasons

**Comment by ThomasLecocq** [comment]
I guessed so, anyway :-) Add your name to the notebook + the readme and I'll merge!

**Comment by claudiodsf** [comment]
Hi Fred, why you created a new notebook (named `FMassinSocialDistancing.ipynb`) instead of modifying the existing one?

**Comment by FMassin** [comment]
Because I don't want to erase the original example plots from a single channel. This example is still the best for simple demo. Plus modification tracking on notebooks is clunky.

**Comment by claudiodsf** [comment]
> Because I don't want to erase the original example plots from a single channel. This example is still the best for simple demo. Plus modification tracking on notebooks is clunky.

I think this is confusing. IMHO, we should keep just one notebook with options for different use cases.

**Comment by FMassin** [comment]
So you want me to put that in the original nb and recompute everything with the original example station? More work, thanks @claudiodsf I missed working with you :D

**Comment by claudiodsf** [comment]
That's just my humble opinion 😉  Let's see what the big boss @ThomasLecocq thinks 😝

**Comment by ThomasLecocq** [comment]
for now I think it's fine to duplicate. And thanks @claudiodsf for proposing to clean that mess by writing clear functions & toobox ;-)

**Comment by FMassin** [comment]
> That's just my humble opinion 😉 Let's see what the big boss @ThomasLecocq thinks 😝

Well I did it anyway. No worries it was valuable exercice since I fixed some mistakes.

**Comment by claudiodsf** [comment]
Wait, Tom already merged this one !

**Comment by ThomasLecocq** [comment]
what if I named you two co-dev on this project repo ? :-)

**Comment by FMassin** [comment]
I Think

> Wait, Tom already merged this one !

I don't there's any harm here, `FMassinSocialDistancing.ipynb` is an SED example, next #5 makes the SED and ODC example similar...

**Pull request merged**
